[package]
name = "tv-ui"
version.workspace = true
edition.workspace = true
default-run = "tv-ui"

[dependencies]
tv-core = { path = "../tv-core" }
serde.workspace = true
ron.workspace = true

[dependencies.windows]
version = "0.62"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
]
